/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef LIVROTHEQUE_PRIVATE_H
#define LIVROTHEQUE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.6.9"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	6
#define VER_BUILD	9
#define COMPANY_NAME	"Fougnyland"
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"La Livrotheque par Fougny & Co"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Livrotheque.exe"
#define PRODUCT_NAME	"Livrotheque"
#define PRODUCT_VERSION	""

#endif /*LIVROTHEQUE_PRIVATE_H*/
