// Class automatically generated by Dev-C++ New Class wizard

#ifndef ARBOCTRLIEMDATA_H
#define ARBOCTRLIEMDATA_H

#include <wx/treebase.h> // inheriting class's header file

#include <wx/string.h>

enum E_typeNoeudArboCtrl {
    E_TNAC_racine,
    E_TNAC_lettre,
    E_TNAC_table
};

/*
 * No description
 */
class arboCtrlItemData : public wxTreeItemData
{
public:
	// class constructor
	arboCtrlItemData(E_typeNoeudArboCtrl typeNoeud, wxString table, long valeurNoeud)
        {m_typeNoeud = typeNoeud; m_table = table; m_valeurNoeud = valeurNoeud;};
	// class destructor
	~arboCtrlItemData() {};

    E_typeNoeudArboCtrl typeNoeud() const {return m_typeNoeud;}
    long valeurNoeud() const {return m_valeurNoeud;}
    wxString table() const {return m_table;}
    wxString cle() const {return wxString::Format("[%d|%s|%ld]", m_typeNoeud, m_table.c_str(), m_valeurNoeud);}

private:
    E_typeNoeudArboCtrl m_typeNoeud;
    wxString m_table;           // champ ou table (ex : auteur, serie)
    long m_valeurNoeud;         // rowid dans le cas général, -1 pour une lettre initiale, -2 pour <null>
};

#endif // ARBOCTRLIEMDATA_H
